version: '3.8'

services:
  minecraft:
    image: nimmis/spigot
    ports:
      - "25565:25565"
      - "25575:25575"
      - "8123:8123"
    volumes:
      - .:/minecraft
    environment:
      - SPIGOT_VER=1.19.4
      - EULA=true
      - MC_MAXMEM=2g